name: Build and Deploy Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Testing
    env:
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install & setup python version 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name : update pip
        run : python -m pip install --upgrade pip
      - name : Install dependencies
        run : pip install -r requirements.txt
      - name : run tests
        run : |
          pip install pytest
          pytest

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-test:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: Production
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: deploying to ubuntu machine
        uses: appleboy/ssh-action@master
        with:
          host: 13.201.225.129
          username: ubuntu
          key: MIIEowIBAAKCAQEAga03Vo9kGPCfktUUtk06C2ArN7XTUs3ysRYFoUyKNLHfUyEuyIfizE5KaTB2NxwUbE8TlL9ccpoLAF1dD9KX6TlcFYLgKIFjcU1U39Qa9Ed7W7Ol8+5XewnX4Fn+8Rnm0R/XFV43p4JyjRvcGshMM5Ms/ZFRWrOScXjn4JWt3P3kaBuMYrkxFJ2BzT/H/dr42GV0yHfZ9t+QMbY8I89pQ1r4tyaTOYPGFZqj3D1b3C54gRveDDrp4KRmN/19bw64NTjGzkFbjizVqU3Y806cIyAn+XnGS5SDihppNPEQDA42+4OEt1o8/dLKVMwmaToeb43Z8/C7YOpIne9iUjv+SwIDAQABAoIBAADvmBum00key3gK06hxLD8SxZ0UUd8iH2NJzmaYn9K7ieoWrjjCSk/BLOZPdDr3l+okM/b53pfxJq0s/1Py6CfFwzVgiW+hZ29U6IzpAfzLW0eRJ1x4VudLbeRvodhpoHHX8fx0fqBV36/HCLKkyXAB2uxFlTm7XA43mizTx7p1lADszsF8JqcYlXSGQp103W3nswyH3gNV2BmB80uQnXNv9zm78zytBB0OzJEsiqqdG6CE44j4O3p/JkzQvNCc2gt5PP+IAfQ2+yL3IYOqieN+w4zrSBK+JbNmNpbmukw9iwV6KG+1YgCKhYsWXgbPHh/uN20JrhHjYo6+oIm2RBkCgYEAyOzw1oRR3CJyAe6eBY5t2F3TX6y0QerZlou6wLCdmYCMSsrIalVr6Dndz5QD6Cli8UDGvqYCiWqRhg4/R9cPBr19K0HAge1F+yOp56Vk+gXbsLFJkE0TK1KWcarVBeMbAs88wXZ3vvyW6o7Plt4kRYMD+brttcJ0SzizIjAfElUCgYEApTiyux9mt1DBqXxIYbWGoFUoBul5sV/9nxK946C0x508uxM9s6W3GeT8Ww/gxvaSBy677SRRB9jHNsc4L3NgN4QHH7uWPI1z7GlaE4LslJC8l+1abkS+zeiLAk1SDfc+SuS8y/w/MtDIAYqABFpMAX1nC2IWcqOggWJt4/D3rh8CgYAVzE7clwJihYIk34RZSfh0zskNyijMNfRhNsuN+BtA+gc+Xf2cO6Q3T3/W81HxL/xB/CsTp+MCkYM0LfuDibthmdEojjuaXOmIs3fNX84yqcwJwVIfy5zWyGD19/igaOEXTvBidL3NBI5C6DdxQKxitjIKN9NuMqh3OLGGdf4I+QKBgBgk3fF8WD1HntVOpSEqLr81UoEYE0F5Xo2lZnxiGqjk8GACIs0i1UwCa2I/QsCwfYxxJuMzoGe+JPZ7TFmayZ+zOntHpV+56AvPJWuegUYAlJ66/7EHeL6MUewHMot56u9016YTeYTKf7/B5o08SMka8zj1n4QnJyhhIt/hccBPAoGBALg3CXyv9018RaJci6szvLcCM2+x/Y7LlZ8+fl5Zyk6HSQi+oG1jFtdoZIVTUv2hjd+oNvKzlXCgetOErBvv7AokelXbBzyerGBdnQ7iF0MP155HVvwipj+A8oEjDMRcketYxt3Ov0Bdismt4PLnNdehcZiuiLoGmRz6DVNivasU
          script: |
            cd /app/src
            git pull
            sudo systemctl restart api
