name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: Testing
    env:
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install & setup python version 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name : update pip
        run : python -m pip install --upgrade pip
      - name : Install dependencies
        run : pip install -r requirements.txt
      - name : run tests
        run : |
          pip install pytest
          pytest